export type Education = "high_school" | "bachelor" | "master" | "phd";

export type TargetRegion =
  | "canada"
  | "uk"
  | "australia-new-zealand"
  | "germany-nordics"
  | "southern-europe"
  | "middle-east"
  | "usa"
  | "sg-my"
  | "jp-kr"
  | "easy-entry";

export type EnglishTest = "none" | "ielts" | "toefl";
export type Goal = "work" | "study" | "pr";

export type VisaProfile = {
  nationality: string;
  targetRegion: TargetRegion;
  age: number;
  education: Education;
  yearsExperience: number;
  fieldOfWork: string;
  englishTest: EnglishTest;
  /** IELTS ~0–9, TOEFL ~0–120; null if not provided */
  testScore: number | null;
  savingsUsd: number;
  goal: Goal;
};

// --- Phase 1: AI Architecture Domain Models ---

export type CEFRLevel = "none" | "A1" | "A2" | "B1" | "B2" | "C1" | "C2";

export type NormalizedProfile = {
  original: VisaProfile;
  canonicalOccupation: string;
  languageLevelCEFR: CEFRLevel;
  isSTEM: boolean;
  isHealthcare: boolean;
};

export type EligibilityStatus = 
  | "ELIGIBLE"
  | "LIKELY_ELIGIBLE"
  | "CONDITIONAL"
  | "NOT_ELIGIBLE"
  | "INSUFFICIENT_EVIDENCE";

export type EligibilityConfidence = "HIGH" | "MEDIUM" | "LOW";

export type RequirementType = "hard" | "conditional" | "points";

export type Requirement = {
  id: string;
  type: RequirementType;
  description: string;
};

export type EvaluatedRequirement = Requirement & {
  met: boolean;
  notes?: string;
};

export type DeterministicEvaluation = {
  pathwayId: string;
  status: EligibilityStatus;
  baseScore: number;
  maxScore: number;
  satisfiedRequirements: EvaluatedRequirement[];
  missingRequirements: EvaluatedRequirement[];
  blockingRequirements: EvaluatedRequirement[];
};

export type RecommendationConfidence = "HIGH" | "MEDIUM" | "LOW";
export type DataFreshness = "VERIFIED" | "STALE" | "UNKNOWN";

export type Citation = {
  title: string;
  url: string;
};

export type RankedPathway = DeterministicEvaluation & {
  // Descriptive fields from Domain Model
  name: string;
  country: string;
  
  // LLM generated fields based on the deterministic evaluation
  reason: string;
  weaknesses: string[];
  documents: string[];
  next_steps: string[];
  citations: Citation[];
  estimated_timeline: string;
  top_improvement: string;
  
  // Confidence metadata
  eligibility_confidence: EligibilityConfidence;
  recommendation_confidence: RecommendationConfidence;
  evidence_confidence: RecommendationConfidence;
  source_freshness: DataFreshness;
};

export type ScoreResponse = {
  overall_score: number; // calculated deterministically or from top pathway
  summary: string;       // generated by LLM
  pathways: RankedPathway[]; // ranked by recommendation engine
};
